// Generated by CoffeeScript 1.10.0
(function() {
  var $, Album, AlbumsList, Backbone, Mn, _, app;

  $ = require("jquery");

  Backbone = require("backbone");

  Mn = require("backbone.marionette");

  _ = require("underscore");

  app = new Backbone.Marionette.Application;

  Album = Mn.LayoutView.extend({
    tagName: 'li',
    template: _.template('<%- albumName %> &mdash; <%- id %>')
  });

  AlbumsList = Mn.CollectionView.extend({
    el: '#albums',
    tagName: 'ul',
    childView: Album
  });

  console.log(AlbumsList);

  albums.render();

}).call(this);
