// Generated by CoffeeScript 1.10.0
(function() {
  var $, Album, AlbumsCollection, AlbumsList, Backbone, Mn, _, albums, app;

  $ = require("jquery");

  Backbone = require("backbone");

  Mn = require("backbone.marionette");

  _ = require("underscore");

  app = new Backbone.Marionette.Application({});

  AlbumsCollection = new Backbone.Collection;

  AlbumsCollection.url = '/albums';

  AlbumsCollection.fetch();

  Album = Mn.ItemView.extend({
    tagName: 'li',
    template: _.template('<%- albumName %> &mdash; <%- id %>')
  });

  AlbumsList = Mn.CollectionView.extend({
    el: '#albums',
    tagName: 'ul',
    childView: Album
  });

  albums = new AlbumsList({
    collection: AlbumsCollection
  });

  albums.render();

}).call(this);
