// Generated by CoffeeScript 1.10.0
(function() {
  var $, Backbone, Mn, TestObj, _, app, test;

  $ = require("jquery");

  Backbone = require("backbone");

  Mn = require("backbone.marionette");

  _ = require("underscore");

  app = new Backbone.Marionette.Application({});

  TestObj = new Mn.Object.extend({
    initialize: function() {
      albumsCollection.fetch();
      return alert("lafew");
    },
    albumsCollection: new Backbone.Collection({
      url: '/albums'
    })
  });

  test = new TestObj({});

}).call(this);
