AppBundle\Entity\Album:
    type: entity
    table: albums
    repositoryClass: AppBundle\Repository\AlbumRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        albumName:
            type: string
            length: 255
            column: album_name
        created:
            type: datetime
        updated:
            type: datetime
            nullable: true
    lifecycleCallbacks:
            prePersist: [setCreatedValue]
            preUpdate:  [setUpdatedValue]