AppBundle\Entity\Image:
    type: entity
    table: images
    repositoryClass: AppBundle\Repository\ImageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        imageName:
            type: string
            length: 255
            unique: true
            column: image_name
        created:
            type: datetime
        updated:
            type: datetime
            nullable: true
    manyToOne:
            album:
                targetEntity: AppBundle\Entity\Album
                joinColumn:
                    name: album_id
                    referencedColumnName: id
                    nullable: true
    lifecycleCallbacks:
                prePersist: [setCreatedValue]
                preUpdate:  [setUpdatedValue]