AppBundle\Entity\Image:
    type: entity
    table: images
    repositoryClass: AppBundle\Repository\ImageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        imageName:
            type: string
            length: 255
            column: image_name
        created:
            type: datetime
        updated:
            type: datetime
            nullable: true
    manyToOne:
        album:
            targetEntity: AppBundle\Entity\Album
            inversedBy: images
            fetch: LAZY
            joinColumn:
                name: album_id
                referencedColumnName: id
    lifecycleCallbacks:
                prePersist: [setCreatedValue]
                preUpdate:  [setUpdatedValue]