<?php

namespace Payever\TestBundle\Repository;

use Payever\TestBundle\Entity\Album;
/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends \Doctrine\ORM\EntityRepository
{
	public function getAlbumImagesQuery($albumId, $page, \Knp\Component\Pager\Paginator $paginator){
		$result = [];
		$query = $this->createQueryBuilder('i');
		$query->where('i.album = :album');
		$query->setParameter('album', $albumId);

		/** @var \Knp\Component\Pager\Paginator $paginator */
		$pagination = $paginator->paginate(
			$query->getQuery(),
			$page,
			Album::MAX_IMAGES_PER_PAGE
		);

		foreach ($pagination->getItems() as $item) {
			$result[] = $item->toJson();
		}
		
		return $result;
	}
}
